// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	infrastructure "github.com/christhianjesus/bia-challenge/internal/infrastructure"
	mock "github.com/stretchr/testify/mock"
)

// SQLClient is an autogenerated mock type for the SQLClient type
type SQLClient struct {
	mock.Mock
}

// QueryContext provides a mock function with given fields: ctx, query, args
func (_m *SQLClient) QueryContext(ctx context.Context, query string, args ...interface{}) (infrastructure.SQLRows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 infrastructure.SQLRows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (infrastructure.SQLRows, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) infrastructure.SQLRows); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(infrastructure.SQLRows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSQLClient creates a new instance of SQLClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSQLClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SQLClient {
	mock := &SQLClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
