// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AddressRepository is an autogenerated mock type for the AddressRepository type
type AddressRepository struct {
	mock.Mock
}

// GetByMetersIDs provides a mock function with given fields: ctx, metersIDs
func (_m *AddressRepository) GetByMetersIDs(ctx context.Context, metersIDs []int) (map[int]string, error) {
	ret := _m.Called(ctx, metersIDs)

	var r0 map[int]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) (map[int]string, error)); ok {
		return rf(ctx, metersIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int) map[int]string); ok {
		r0 = rf(ctx, metersIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, metersIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAddressRepository creates a new instance of AddressRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressRepository {
	mock := &AddressRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
